### ISSUE TITLE
Database backup error: Command `pg_dump` not found.

### ISSUE THREAD

**Issue by jujes** [dantot/docker-odoo10#1]
Hi, someone know how fix it?

if I use  **localhost:8069/web/database/backup**

```
Database backup error: Command `pg_dump` not found.
```

or using **phppgadmin**

```
Export error: Failed to execute pg_dump (given path in your conf/config.inc.php : /usr/bin/pg_dump). Please, fix this path in your configuration and relog.
```

thanks in advance,

**Comment by dantot** [comment]
Hi jujes!

I have already fixed it using new tag/branch with postgres-backup name.

Thanks for use!
